Build all containers

diff --git a/.github/workflows/build-docker-images.yml b/.github/workflows/build-docker-images.yml
--- a/.github/workflows/build-docker-images.yml
+++ b/.github/workflows/build-docker-images.yml
@@ -20,17 +20,18 @@ on:
 
 # Testing building all these containers into my own account.
 jobs:
+  # Build containers that support x86 only
   build_x86:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         IMAGE:
           #- {TAG_NAME: "gwblake/cryptography-runner-centos7", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/centos7"}
-          - {TAG_NAME: "gwblake/cryptography-runner-centos8", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/centos8"}
+          #- {TAG_NAME: "gwblake/cryptography-runner-centos8", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/centos8"}
           #- {TAG_NAME: "gwblake/cryptography-runner-centos8-fips", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/centos8", BUILD_ARGS: "--build-arg FIPS=1"}
 
           #- {TAG_NAME: "gwblake/cryptography-runner-fedora", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/fedora"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-alpine", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/alpine"}
+          - {TAG_NAME: "gwblake/cryptography-runner-alpine", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/alpine"}
 
           #- {TAG_NAME: "gwblake/cryptography-runner-stretch", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=stretch"}
           #- {TAG_NAME: "gwblake/cryptography-runner-buster", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=buster"}
@@ -41,8 +42,8 @@ jobs:
           #- {TAG_NAME: "gwblake/cryptography-runner-ubuntu-focal", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=focal"}
           #- {TAG_NAME: "gwblake/cryptography-runner-ubuntu-rolling", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=rolling"}
 
-          #- {TAG_NAME: "gwblake/cryptography-manylinux1", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux1"}
-          #- {TAG_NAME: "gwblake/cryptography-manylinux2010", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux2010"}
+          - {TAG_NAME: "gwblake/cryptography-manylinux1", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux1"}
+          - {TAG_NAME: "gwblake/cryptography-manylinux2010", ARCH_TAG: "x86_64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux2010"}
 
 
     name: "Building docker image ${{ matrix.IMAGE.TAG_NAME }}"
@@ -52,9 +53,9 @@ jobs:
       # Sometimes we add new docker images and if they've never been pushed
       # they can't be pulled.
       - name: Pull existing image
-        run: docker pull ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }} || true
+        run: docker pull ${{ matrix.IMAGE.TAG_NAME }} || true
       - name: Build image
-        run: docker build --pull --cache-from ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }} -t ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }} ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
+        run: docker build --pull --cache-from ${{ matrix.IMAGE.TAG_NAME }} -t ${{ matrix.IMAGE.TAG_NAME }} ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
       - name: Login to docker
         run: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"'
         env:
@@ -62,32 +63,31 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
       - name: Push image
-        run: docker push ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }}
+        run: docker push ${{ matrix.IMAGE.TAG_NAME }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
 
-  # There are some containers we simply can't build on Arm right now
-  build_aarch64:
-    # needs: build_x86
+  # Build the containers we can that support both arm64 and x86_64
+  build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         IMAGE:
-          #- {TAG_NAME: "gwblake/cryptography-runner-centos7", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/centos7"}
+          - {TAG_NAME: "gwblake/cryptography-runner-centos7", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/centos7"}
           - {TAG_NAME: "gwblake/cryptography-runner-centos8", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/centos8"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-centos8-fips", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/centos8", BUILD_ARGS: "--build-arg FIPS=1"}
+          - {TAG_NAME: "gwblake/cryptography-runner-centos8-fips", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/centos8", BUILD_ARGS: "--build-arg FIPS=1"}
 
-          #- {TAG_NAME: "gwblake/cryptography-runner-fedora", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/fedora"}
+          - {TAG_NAME: "gwblake/cryptography-runner-fedora", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/fedora"}
 
-          #- {TAG_NAME: "gwblake/cryptography-runner-stretch", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=stretch"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-buster", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=buster"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-bullseye", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=bullseye"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-sid", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=sid"}
+          - {TAG_NAME: "gwblake/cryptography-runner-stretch", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=stretch"}
+          - {TAG_NAME: "gwblake/cryptography-runner-buster", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=buster"}
+          - {TAG_NAME: "gwblake/cryptography-runner-bullseye", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=bullseye"}
+          - {TAG_NAME: "gwblake/cryptography-runner-sid", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/debian", BUILD_ARGS: "--build-arg RELEASE=sid"}
 
-          #- {TAG_NAME: "gwblake/cryptography-runner-ubuntu-bionic", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=bionic"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-ubuntu-focal", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=focal"}
-          #- {TAG_NAME: "gwblake/cryptography-runner-ubuntu-rolling", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=rolling"}
+          - {TAG_NAME: "gwblake/cryptography-runner-ubuntu-bionic", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=bionic"}
+          - {TAG_NAME: "gwblake/cryptography-runner-ubuntu-focal", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=focal"}
+          - {TAG_NAME: "gwblake/cryptography-runner-ubuntu-rolling", ARCH_TAG: "arm64", DOCKERFILE_PATH: "runners/ubuntu", BUILD_ARGS: "--build-arg RELEASE=rolling"}
 
-          #- {TAG_NAME: "gwblake/cryptography-manylinux2014_aarch64", ARCH_TAG: "arm64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux2014_aarch64"}
+          # - {TAG_NAME: "gwblake/cryptography-manylinux2014_aarch64", ARCH_TAG: "arm64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux2014_aarch64"}
 
 
     name: "Building docker image ${{ matrix.IMAGE.TAG_NAME }}"
@@ -103,31 +103,62 @@ jobs:
       # Sometimes we add new docker images and if they've never been pushed
       # they can't be pulled.
       - name: Pull existing image
-        run: docker pull ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }} || true
+        run: docker pull ${{ matrix.IMAGE.TAG_NAME }}:latest || true
       - name: Build image
         run: >
-          docker buildx build --platform linux/arm64 --pull --cache-from ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }}
+          docker buildx build --platform linux/arm64,linux/amd64 --pull --cache-from ${{ matrix.IMAGE.TAG_NAME }}
           --cache-to "type=local,dest=/tmp/.buildx-cache" --output "type=image,push=false"
-          -t ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }} ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
+          -t ${{ matrix.IMAGE.TAG_NAME }} ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
       - name: Login to docker
         run: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"'
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
-      - name: Show images
-        run: docker images
       - name: Push image
         run: >
           docker buildx build --cache-from "type=local,src=/tmp/.buildx-cache"
-          --platform linux/arm64,linux/amd64 --output "type=image,push=true" -t ${{ matrix.IMAGE.TAG_NAME }}:${{ matrix.IMAGE.ARCH_TAG }}
+          --platform linux/arm64,linux/amd64 --output "type=image,push=true" -t ${{ matrix.IMAGE.TAG_NAME }}
           ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
-      - name: Enable experimental docker features
-        run: 'echo "{\"experimental\": true}" | sudo tee -a /etc/docker/daemon.json'
-      - name: Create a manifest
-        run: docker manifest create ${{ matrix.IMAGE.TAG_NAME }}:latest --amend ${{ matrix.IMAGE.TAG_NAME }}:x86_64 --amend ${{ matrix.IMAGE.TAG_NAME }}:arm64
+
+  # Build the containers that only support aarch64
+  build_aarch64:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        IMAGE:
+          - {TAG_NAME: "gwblake/cryptography-manylinux2014_aarch64", ARCH_TAG: "arm64", DOCKERFILE_PATH: "cryptography-manylinux", BUILD_ARGS: "-f cryptography-manylinux/Dockerfile-manylinux2014_aarch64"}
+
+
+    name: "Building docker image ${{ matrix.IMAGE.TAG_NAME }}"
+    steps:
+      - uses: actions/checkout@master
+      - name: Docker Buildx
+        id: buildx
+        uses: crazy-max/ghaction-docker-buildx@v3.3.0
+        with:
+          buildx-version: latest
+          qemu-version: latest
+      # Pull the previous image, but if it fails return true anyway.
+      # Sometimes we add new docker images and if they've never been pushed
+      # they can't be pulled.
+      - name: Pull existing image
+        run: docker pull ${{ matrix.IMAGE.TAG_NAME }}:latest || true
+      - name: Build image
+        run: >
+          docker buildx build --platform linux/arm64 --pull --cache-from ${{ matrix.IMAGE.TAG_NAME }}
+          --cache-to "type=local,dest=/tmp/.buildx-cache" --output "type=image,push=false"
+          -t ${{ matrix.IMAGE.TAG_NAME }} ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
+      - name: Login to docker
+        run: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"'
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
-      - name: Push multi-arch manifest
-        run: docker manifest push ${{ matrix.IMAGE.TAG_NAME }}:latest
+      - name: Push image
+        run: >
+          docker buildx build --cache-from "type=local,src=/tmp/.buildx-cache"
+          --platform linux/arm64 --output "type=image,push=true" -t ${{ matrix.IMAGE.TAG_NAME }}
+          ${{ matrix.IMAGE.DOCKERFILE_PATH }} ${{ matrix.IMAGE.BUILD_ARGS }}
         if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/manylinux2014_aarch64' #&& github.ref == 'refs/heads/master'
